# Generated by Django 5.1 on 2025-04-02 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMOON_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='المسمى الوظيفي')),
                ('summary', models.TextField(verbose_name='ملخص عنك')),
                ('skills', models.TextField(verbose_name='المهارات (افصل بينها بفواصل)')),
                ('experience', models.TextField(verbose_name='الخبرات العملية')),
                ('education', models.TextField(verbose_name='المؤهلات العلمية')),
                ('languages', models.TextField(verbose_name='اللغات (افصل بينها بفواصل)')),
                ('certifications', models.TextField(blank=True, verbose_name='الشهادات والدورات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cv', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100, verbose_name='الدرجة العلمية')),
                ('institution', models.CharField(max_length=100, verbose_name='المؤسسة التعليمية')),
                ('field_of_study', models.CharField(max_length=100, verbose_name='التخصص')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('currently_studying', models.BooleanField(default=False, verbose_name='ما زلت أدرس هنا')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='AMOON_app.cv')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100, verbose_name='المسمى الوظيفي')),
                ('company', models.CharField(max_length=100, verbose_name='الشركة')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('currently_working', models.BooleanField(default=False, verbose_name='ما زلت أعمل هنا')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='AMOON_app.cv')),
            ],
        ),
    ]
