# Generated by Django 5.1 on 2025-04-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMOON_app', '0002_cv_education_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='employee_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
