# Generated by Django 5.1 on 2025-04-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMOON_app', '0003_company_employee_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
