# Generated by Django 5.1 on 2025-04-05 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMOON_app', '0004_cv_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='languages',
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان الشهادة')),
                ('institution', models.CharField(max_length=100, verbose_name='المؤسسة المانحة')),
                ('date_obtained', models.DateField(verbose_name='تاريخ الحصول عليها')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='AMOON_app.cv')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اللغة')),
                ('proficiency', models.CharField(choices=[('beginner', 'مبتدئ'), ('intermediate', 'متوسط'), ('advanced', 'متقدم'), ('native', 'لغة أم')], max_length=20, verbose_name='مستوى الإتقان')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='AMOON_app.cv')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='المهارة')),
                ('proficiency', models.CharField(choices=[('beginner', 'مبتدئ'), ('intermediate', 'متوسط'), ('advanced', 'متقدم')], max_length=20, verbose_name='مستوى الإتقان')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Skill', to='AMOON_app.cv')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='AMOON_app.cv')),
            ],
        ),
    ]
