# Generated by Django 5.1 on 2025-04-05 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AMOON_app', '0005_remove_cv_certifications_remove_cv_languages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='education',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='updated_at',
        ),
    ]
