# Generated by Django 5.1 on 2025-04-05 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMOON_app', '0006_remove_cv_created_at_remove_cv_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='AMOON_app.cv'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.CharField(choices=[('beginner', 'مبتدئ'), ('intermediate', 'متوسط'), ('advanced', 'متقدم')], max_length=20),
        ),
    ]
