# Generated by Django 5.1 on 2025-04-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMOON_app', '0007_alter_skill_cv_alter_skill_proficiency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.IntegerField(choices=[(20, 'مبتدئ (20%)'), (40, 'مبتدئ متقدم (40%)'), (60, 'متوسط (60%)'), (80, 'متقدم (80%)'), (100, 'خبير (100%)')], default=30),
        ),
    ]
